services:
  db:
    build: db
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  webform:
    build:
      context: webform/
    restart: always
    depends_on:
      - db
    networks:
      - backend

  weblist:
    build:
      context: weblist/
    restart: always
    depends_on:
      - db
    networks:
      - backend

  proxy:
    build: proxy
    restart: always
    ports:
      - 80:80
      - 81:81
    depends_on: 
      - webform
      - weblist
    networks:
      - frontend
      - backend

volumes:
  db-data:

networks:
  frontend: {}
  backend: {}
