services:
  db:
    build: db
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  webform:
    build:
      context: webform/
    restart: always
    depends_on:
      - db
    networks:
      - backend

  backend:
    build:
      context: backend
      target: builder
    restart: always
    ports:
      - 8000:8000
    depends_on: [db]

  proxy:
    build: proxy
    restart: always
    ports:
      - 80:80
    depends_on: 
      - backend

volumes:
  db-data:
