services:
  #db:
    #image: postgres
    #restart: always
    #user: postgres
    #volumes:
      #- db-data:/var/lib/postgresql/newdata
    #environment:
      #- POSTGRES_DB=example
      #- POSTGRES_HOST_AUTH_METHOD=trust
    #expose:
      #- 5432
    #healthcheck:
      #test: [ "CMD", "pg_isready" ]
      #interval: 10s
      #timeout: 5s
      #retries: 5

  backend:
    build:
      context: backend
      target: builder
    restart: always
    ports:
      - 8000:8000
    depends_on: [db]

  proxy:
    build: proxy
    restart: always
    ports:
      - 80:80
    depends_on: 
      - backend

volumes:
  db-data:
